# Generated by Django 5.1.5 on 2025-02-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profle_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
