# Generated by Django 5.1.5 on 2025-02-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
