# Generated by Django 4.0.3 on 2024-09-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0002_size_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
