# Generated by Django 5.1.5 on 2025-02-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0002_alter_imagealbum_options_remove_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
