# Generated by Django 5.1.5 on 2025-02-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0002_user_profle_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profle_pic',
            new_name='profile_pic',
        ),
    ]
