# Generated by Django 5.1.5 on 2025-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0003_remove_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
