# Generated by Django 5.1.5 on 2025-02-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0003_remove_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='image',
        ),
    ]
