# Generated by Django 5.1.5 on 2025-02-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
