# Generated by Django 5.1.5 on 2025-02-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0005_wishlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='Wishlist',
        ),
    ]
