# Generated by Django 5.1.5 on 2025-02-25 07:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0006_rename_wishlistitem_wishlist'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-added_at']},
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='current_redemptions',
            new_name='used',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applies_to_all_products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_redemptions',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='one_time_use',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='stackable',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mbase.discount'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['content_type', 'object_id'], name='Mbase_disco_content_a36bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['start_date', 'end_date'], name='Mbase_disco_start_d_509b61_idx'),
        ),
    ]
