# Generated by Django 4.0.3 on 2024-09-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0007_alter_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
    ]
