# Generated by Django 5.1.5 on 2025-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0007_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Trending', 'Trending'), ('Exclusive', 'Exclusive'), ('Limited Edition', 'Limited Edition')], max_length=20, null=True),
        ),
    ]
