# Generated by Django 4.0.3 on 2024-05-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0008_rename_image_orderitem_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(help_text='Hex color code, e.g., #FFFFFF for white', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='Mbase.color'),
        ),
    ]
