# Generated by Django 5.1.5 on 2025-02-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0008_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
    ]
