# Generated by Django 5.1.5 on 2025-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='Mbase.category'),
        ),
    ]
