# Generated by Django 4.0.3 on 2024-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0010_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
