# Generated by Django 5.1.5 on 2025-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0010_coupon_coupon_scope_discount_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
