# Generated by Django 4.0.3 on 2024-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0010_remove_product_category_category_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('no_of_days', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
