# Generated by Django 5.1.5 on 2025-02-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0011_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
