# Generated by Django 4.0.3 on 2024-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0011_discountoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountoffers',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
