# Generated by Django 4.0.3 on 2024-09-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0011_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
