# Generated by Django 4.0.3 on 2024-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0012_discountoffers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffers',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
