# Generated by Django 5.1.5 on 2025-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0013_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='genre',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
