# Generated by Django 5.1.5 on 2025-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0014_delete_mymodel_genre_image_file_id_genre_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
