# Generated by Django 4.0.3 on 2024-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0015_discountoffers_countinstock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffers',
            name='end_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
