# Generated by Django 5.1.5 on 2025-02-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0015_user_profile_pic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile_pic_url',
        ),
    ]
