# Generated by Django 4.0.3 on 2024-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0016_alter_discountoffers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffers',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
