# Generated by Django 4.0.3 on 2024-08-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0018_remove_discountoffers_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountoffers',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discountoffers',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
